apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: batman-lab-dev
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: <DIN_GIT_REPO_URL>
    targetRevision: master
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: batman-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  